apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-assessment-config
  namespace: devops-assessment
data:
  APP_NAME: "devops-assessment-api"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  HOST: "0.0.0.0"
  PORT: "8000"