apiVersion: v1
kind: Service
metadata:
  name: devops-assessment-service
  namespace: devops-assessment
spec:
  selector:
    app: devops-assessment-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort